# Generated by Django 3.2.8 on 2021-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], max_length=20, null=True)),
            ],
        ),
    ]
