# Generated by Django 3.2.8 on 2021-10-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20211013_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completed',
            options={'verbose_name_plural': 'Completed'},
        ),
        migrations.AlterModelOptions(
            name='current',
            options={'verbose_name_plural': 'Current'},
        ),
    ]
