# Generated by Django 3.2.8 on 2021-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20211013_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='quantity',
        ),
        migrations.AddField(
            model_name='completed',
            name='status',
            field=models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], max_length=20, null=True),
        ),
    ]
