# Generated by Django 3.2.8 on 2021-10-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_completed_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='status',
        ),
        migrations.AlterField(
            model_name='completed',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.current'),
        ),
    ]
