# Generated by Django 3.2.8 on 2021-10-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20211014_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.current'),
        ),
    ]
