# Generated by Django 3.2.8 on 2021-10-14 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20211014_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
